
ALLOWED_METHODS = ['*']
ALLOWED_ORIGINS = ["http://localhost:3000"]
ALLOWED_ORIGINS_PATTERNS = []
ALLOWED_HEADERS = ['*']
EXPOSED_HEADERS = []
MAX_AGE = 0
SUPPORTS_CREDENTIALS = False
CORS_ALLOW_ALL_ORIGINS = False